name: CI - Go API con E2E y Performance

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-e2e-and-performance:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🧰 Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: 📦 Instalar dependencias Go
        run: go mod tidy

      - name: 🧪 Instalar Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser fonts-liberation

      - name: 🚀 Levantar servidor Go en background
        run: |
          nohup go run main.go > server.log 2>&1 &
          sleep 5

      - name: 🧪 Ejecutar pruebas End-to-End con chromedp
        env:
          CHROME_PATH: /usr/bin/chromium-browser
        run: |
          echo "▶ Ejecutando pruebas E2E"
          go test ./tests -run TestEndToEnd -v -count=1

      - name: 🚀 Ejecutar prueba de performance con vegeta
        run: |
          echo "▶ Ejecutando prueba de performance"
          go test ./tests -run TestPerformanceCreateSubjects -v -count=1
