name: Api para pruebas end to end y perfomance

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-e2e-and-performance:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Configura el Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Instala las dependencias del proyecto
        run: go mod tidy

      - name: Instala Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser fonts-liberation

      - name: Levanta el servidor Golang en background
        run: |
          nohup go run main.go > server.log 2>&1 &
          sleep 5

      - name: Ejecuta la prueba End-to-End con chromedp
        env:
          CHROME_PATH: /usr/bin/chromium-browser
        run: |
          echo "Ejecutando la prueba end to end"
          go test ./tests -run TestEndToEnd -v -count=1

      - name: Ejecuta la prueba de performance con vegeta
        run: |
          echo "Ejecutando la prueba de performance"
          go test ./tests -run TestPerformanceCreateSubjects -v -count=1